# Generated by Django 5.0.6 on 2024-06-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentDetails',
            new_name='student',
        ),
    ]
