# Generated by Django 5.0.6 on 2024-06-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_studentdetails_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField(max_length=20)),
                ('gender', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('shift', models.CharField(max_length=50)),
            ],
        ),
    ]
